title: Gradle 中文用户组
subtitle: "一款简洁而优雅的构建工具."
description: "基于groovy DSL的后现代脚本化构建工具."
author: PKAQ
language: zh-cn
timezone: UTC
url: https://gradlecn.org
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: https://github.com/gradlecn/gradlecn.github.io.git

duoshuo: 
	shortname: gradlecn
google_analytics: UA-83547859-1
fb_admins: 100000247608790
algolia:
  zh-cn:
    api_key: 833e76b8e5868b5ca61c5725dcabe526
    index_name: gradle_zh-cn
twitter: gradlecn
github: gradle/gradle
